os:
- osx
script: $FORMULAE="";for file in ./Formula/*.rb; do echo "Testing $file"; $FORMULAE<<"$file & ";done;$FORMULAE<<wait;brew audit $FORMULAE --online;
git:
  depth: 1
branches:
  only:
  - master
cache:
notifications:
  email: false
