sudo: false

os:
- osx

before_script: brew update
script: for file in ./Formula/*.rb; do echo "Testing $file"; brew audit $file --online; done

git:
  depth: 1

branches:
  only:
  - master

before_cache:
  - brew cleanup

cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Homebrew

notifications:
  email: false
