os:
- osx
before_script: brew update && brew upgrade
script: for file in ./Formula/*.rb; do echo "Testing $file"; brew audit $file --online; done
git:
  depth: 1
branches:
  only:
  - master
cache:
notifications:
  email: false
