name: Audit Formulas

on:
  push:
    branches:
      - master

jobs:
  audit:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

    - name: Update Homebrew
      run: brew update

    - name: Tap Repository
      run: brew tap nsis-dev/makensis

    - name: Audit Formulas
      run:  for file in ./Formula/*.rb; do echo "Testing $file"; brew audit NSIS-Dev/makensis/$(basename ${file%.rb}) --online; done
